export const NavbarLinks = [
  { id: 1, name: "Dashboard Library", path: "/" },
  { id: 2, name: "TLC Library", path: "/tlc" },
  { id: 3, name: "TLC User", path: "/users" },
];

export const headerTLC = [
  "time",
  "userfullname",
  "affecteduser",
  "eventcontext",
  "component",
  "eventname",
  "description",
  "origin",
  "ipaddress",
];

export const monthsArray = [
  { value: '01', label: "January" },
  { value: '02', label: "February" },
  { value: '03', label: "March" },
  { value: '04', label: "April" },
  { value: '05', label: "May" },
  { value: '06', label: "June" },
  { value: '07', label: "July" },
  { value: '08', label: "August" },
  { value: '09', label: "September" },
  { value: '10', label: "October" },
  { value: '11', label: "November" },
  { value: '12', label: "December" },
];
export const Colleges = [
  {label: 'ALL', value: 'ALL'},
  // { label: "CAHS", value: "COLLEGE OF ALLIED HEALTH SCIENCES" },
  // { label: "CASE", value: "COLLEGE OF ARTS, SCIENCES AND EDUCATION" },
  // { label: "CBMA", value: "COLLEGE OF BUSINESS, MANAGEMENT & ACCOUNTANCY" },
  // { label: "CEIS", value: "COLLEGE OF ENGINEERING AND INFORMATION SCIENCES" },
  // { label: "CHTM", value: "COLLEGE OF HOSPITALITY AND TOURISM MANAGEMENT" },
  // { label: "CMT", value: "COLLEGE OF MEDICAL TECHNOLOGY" },
  // { label: "SLCN", value: "ST. LUKE’S COLLEGE OF NURSING" },
  // { label: "THS", value: "HIGH SCHOOL" },
  // { label: "GS", value: "GRADUATE SCHOOL" },
];

export const yearsArray = [
  { value: 2018, label: 2018 },
  { value: 2019, label: 2019 },
  { value: 2020, label: 2020 },
  { value: 2021, label: 2021 },
  { value: 2022, label: 2022 },
  { value: 2023, label: 2023 },
  { value: 2024, label: 2024 },
  { value: 2025, label: 2025 },
  { value: 2026, label: 2026 },
  { value: 2027, label: 2027 },
  { value: 2028, label: 2028 },
  { value: 2029, label: 2029 },
  { value: 2030, label: 2030 },
  { value: 2031, label: 2031 },
  { value: 2032, label: 2032 },
  { value: 2033, label: 2033 },
  { value: 2034, label: 2034 },
  { value: 2035, label: 2035 },
  { value: 2036, label: 2036 },
  { value: 2037, label: 2037 },
  { value: 2038, label: 2038 },
  { value: 2039, label: 2039 },
  { value: 2040, label: 2040 },
  { value: 2041, label: 2041 },
  { value: 2042, label: 2042 },
  { value: 2043, label: 2043 },
  { value: 2044, label: 2044 },
  { value: 2045, label: 2045 },
  { value: 2046, label: 2046 },
  { value: 2047, label: 2047 },
  { value: 2048, label: 2048 },
  { value: 2049, label: 2049 },
  { value: 2050, label: 2050 },
];

export const faculties = [
  { value: 'Faculty', label: 'Faculty' },
  { value: 'Students', label: 'Students' },
];

export const TableDataSample = [
  {
      "null": {
          "Aug": 7,
          "Dec": 4,
          "Nov": 29,
          "Oct": 8,
          "Sep": 1,
          "Apr": 25,
          "Feb": 3,
          "Jan": 19,
          "Jun": 1,
          "Mar": 32,
          "May": 19
      },
      "COLLEGE OF ALLIED HEALTH SCIENCES": {
          "Aug": 42,
          "Dec": 10,
          "Nov": 16,
          "Oct": 108,
          "Sep": 20,
          "Apr": 42,
          "Feb": 45,
          "Jan": 28,
          "Jul": 7,
          "Jun": 5,
          "Mar": 45,
          "May": 51
      },
      "COLLEGE OF ARTS, SCIENCES AND EDUCATION": {
          "Aug": 8,
          "Dec": 6,
          "Nov": 20,
          "Oct": 91,
          "Sep": 20,
          "Apr": 50,
          "Feb": 62,
          "Jan": 50,
          "Jul": 10,
          "Jun": 4,
          "Mar": 110,
          "May": 50
      },
      "COLLEGE OF BUSINESS, MANAGEMENT & ACCOUNTANCY": {
          "Aug": 51,
          "Dec": 1,
          "Nov": 5,
          "Oct": 10,
          "Sep": 20,
          "Apr": 18,
          "Feb": 37,
          "Jan": 34,
          "Mar": 68,
          "May": 22
      },
      "COLLEGE OF ENGINEERING AND INFORMATION SCIENCES": {
          "Aug": 31,
          "Nov": 1,
          "Oct": 8,
          "Sep": 14,
          "Apr": 12,
          "Dec": 6,
          "Feb": 19,
          "Jan": 11,
          "Mar": 34,
          "May": 10
      },
      "COLLEGE OF HOSPITALITY AND TOURISM MANAGEMENT": {
          "Aug": 4,
          "Dec": 2,
          "Nov": 12,
          "Oct": 18,
          "Sep": 1,
          "Apr": 29,
          "Feb": 151,
          "Jan": 21,
          "Jul": 5,
          "Mar": 37,
          "May": 11
      },
      "COLLEGE OF MEDICAL TECHNOLOGY": {
          "Aug": 23,
          "Dec": 1,
          "Nov": 10,
          "Oct": 48,
          "Sep": 23,
          "Apr": 57,
          "Feb": 17,
          "Jan": 72,
          "Jul": 1,
          "Jun": 2,
          "Mar": 53,
          "May": 18
      },
      "GRADUATE SCHOOL": {
          "Aug": 49,
          "Dec": 3,
          "Nov": 65,
          "Oct": 17,
          "Sep": 41,
          "Apr": 60,
          "Feb": 39,
          "Jan": 14,
          "Jul": 16,
          "Jun": 20,
          "Mar": 91,
          "May": 32
      },
      "TRINTY HIGH SCHOOL": {
          "Nov": 10,
          "Oct": 32,
          "Sep": 1
      },
      "ST. LUKE’S COLLEGE OF NURSING": {
          "Aug": 236,
          "Dec": 3,
          "Nov": 43,
          "Oct": 185,
          "Sep": 28,
          "Apr": 127,
          "Feb": 129,
          "Jan": 132,
          "Jul": 79,
          "Jun": 62,
          "Mar": 298,
          "May": 123
      }
  }
]